[package]
name = "kakashi-tg-bot-runner"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
open = "5"
reqwest = { version = "0.11", features = ["blocking"] }
